version: "2.1"

services:
  mariadb:
    container_name: "mariadb_docker"
    build: 
      context: .
      dockerfile: "mariadb"
    networks:
      freezer_network:
        ipv4_address: 192.168.0.6
    ports :
      - "3306:3306"
    
  proftpd:
    container_name: "proftpd_docker"
    networks:
      freezer_network:
        ipv4_address: 192.168.0.7
    build:
      context: .
      dockerfile: "proftpd"


  nginx:
    build:
      context: .
      dockerfile: "nginx" 
    container_name: "nginx_docker"
    ports:
      - "80:80"
      - "443:443"
    networks:  
      freezer_network:
        ipv4_address: 192.168.0.5

networks:
  freezer_network:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
